In [1]:
import numpy as np

In [2]:
total_time = np.array([213.07, 258.45, 224.57])
total_time_err = np.array([0.01, 0.01, 0.01])
num_period = np.array([75,91,79])
length = 200.6/100
length_err = 0.3/100

In [ ]:
period = total_time / num_period
period_err = total_time_err / np.sqrt(num_period)

g = 4 * np.pi**2 * length / period**2
g_err = g * np.sqrt((length_err/length)**2 + (2*period_err/period)**2)

In [14]:
period

array([2.84093333, 2.84010989, 2.84265823])

In [15]:
period_err

array([0.00013333, 0.00010989, 0.00012658])

In [4]:
g

array([9.81224945, 9.81794008, 9.80034513])

In [10]:
g_err[0] # statistical error

0.014703227089052438

In [9]:
# upper bound systematic error using differences from "bad" experiments
g_sys_err = g[0] * ((g[1]-g[0])**2 + (g[2]-g[0])**2)**0.5
g_sys_err

0.12946820519613653